//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W88.WebRef.wsDummy {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsDummy.dummyWSSoap")]
    public interface dummyWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummySignin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DummySignin(long operatorId, string dummySiteURL, string loginIP, string memberCode, string password, string paymentGroupPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummySignin", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DummySigninAsync(long operatorId, string dummySiteURL, string loginIP, string memberCode, string password, string paymentGroupPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummySignout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DummySignout(string memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummySignout", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DummySignoutAsync(string memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummySessionCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DummySessionCheck(string sessionId, string dummySiteURL, string loginIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummySessionCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DummySessionCheckAsync(string sessionId, string dummySiteURL, string loginIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummySiteStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DummySiteStatus(string dummySiteURL, long memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummySiteStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DummySiteStatusAsync(string dummySiteURL, long memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummySigninAuto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DummySigninAuto(long operatorId, string dummySiteURL, string loginIP, string memberCode, string memberSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummySigninAuto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DummySigninAutoAsync(long operatorId, string dummySiteURL, string loginIP, string memberCode, string memberSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummyRedirectURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DummyRedirectURL(long operatorId, string dummySiteURL, string paymentGroup, string paymentGroupPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummyRedirectURL", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DummyRedirectURLAsync(long operatorId, string dummySiteURL, string paymentGroup, string paymentGroupPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummyURLs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DummyURLs(long operatorId, long methodId, string paymentGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummyURLs", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DummyURLsAsync(long operatorId, long methodId, string paymentGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummyURLs_Mobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DummyURLs_Mobile(long operatorId, long methodId, string paymentGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummyURLs_Mobile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DummyURLs_MobileAsync(long operatorId, long methodId, string paymentGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummySiteStatusByPaymentGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DummySiteStatusByPaymentGroup(string dummySiteURL, long operatorId, string paymentGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DummySiteStatusByPaymentGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DummySiteStatusByPaymentGroupAsync(string dummySiteURL, long operatorId, string paymentGroup);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface dummyWSSoapChannel : W88.WebRef.wsDummy.dummyWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class dummyWSSoapClient : System.ServiceModel.ClientBase<W88.WebRef.wsDummy.dummyWSSoap>, W88.WebRef.wsDummy.dummyWSSoap {
        
        public dummyWSSoapClient() {
        }
        
        public dummyWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public dummyWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public dummyWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public dummyWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet DummySignin(long operatorId, string dummySiteURL, string loginIP, string memberCode, string password, string paymentGroupPassword) {
            return base.Channel.DummySignin(operatorId, dummySiteURL, loginIP, memberCode, password, paymentGroupPassword);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DummySigninAsync(long operatorId, string dummySiteURL, string loginIP, string memberCode, string password, string paymentGroupPassword) {
            return base.Channel.DummySigninAsync(operatorId, dummySiteURL, loginIP, memberCode, password, paymentGroupPassword);
        }
        
        public int DummySignout(string memberId) {
            return base.Channel.DummySignout(memberId);
        }
        
        public System.Threading.Tasks.Task<int> DummySignoutAsync(string memberId) {
            return base.Channel.DummySignoutAsync(memberId);
        }
        
        public System.Data.DataSet DummySessionCheck(string sessionId, string dummySiteURL, string loginIP) {
            return base.Channel.DummySessionCheck(sessionId, dummySiteURL, loginIP);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DummySessionCheckAsync(string sessionId, string dummySiteURL, string loginIP) {
            return base.Channel.DummySessionCheckAsync(sessionId, dummySiteURL, loginIP);
        }
        
        public System.Data.DataSet DummySiteStatus(string dummySiteURL, long memberId) {
            return base.Channel.DummySiteStatus(dummySiteURL, memberId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DummySiteStatusAsync(string dummySiteURL, long memberId) {
            return base.Channel.DummySiteStatusAsync(dummySiteURL, memberId);
        }
        
        public System.Data.DataSet DummySigninAuto(long operatorId, string dummySiteURL, string loginIP, string memberCode, string memberSessionId) {
            return base.Channel.DummySigninAuto(operatorId, dummySiteURL, loginIP, memberCode, memberSessionId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DummySigninAutoAsync(long operatorId, string dummySiteURL, string loginIP, string memberCode, string memberSessionId) {
            return base.Channel.DummySigninAutoAsync(operatorId, dummySiteURL, loginIP, memberCode, memberSessionId);
        }
        
        public System.Data.DataSet DummyRedirectURL(long operatorId, string dummySiteURL, string paymentGroup, string paymentGroupPassword) {
            return base.Channel.DummyRedirectURL(operatorId, dummySiteURL, paymentGroup, paymentGroupPassword);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DummyRedirectURLAsync(long operatorId, string dummySiteURL, string paymentGroup, string paymentGroupPassword) {
            return base.Channel.DummyRedirectURLAsync(operatorId, dummySiteURL, paymentGroup, paymentGroupPassword);
        }
        
        public System.Data.DataSet DummyURLs(long operatorId, long methodId, string paymentGroup) {
            return base.Channel.DummyURLs(operatorId, methodId, paymentGroup);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DummyURLsAsync(long operatorId, long methodId, string paymentGroup) {
            return base.Channel.DummyURLsAsync(operatorId, methodId, paymentGroup);
        }
        
        public System.Data.DataSet DummyURLs_Mobile(long operatorId, long methodId, string paymentGroup) {
            return base.Channel.DummyURLs_Mobile(operatorId, methodId, paymentGroup);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DummyURLs_MobileAsync(long operatorId, long methodId, string paymentGroup) {
            return base.Channel.DummyURLs_MobileAsync(operatorId, methodId, paymentGroup);
        }
        
        public System.Data.DataSet DummySiteStatusByPaymentGroup(string dummySiteURL, long operatorId, string paymentGroup) {
            return base.Channel.DummySiteStatusByPaymentGroup(dummySiteURL, operatorId, paymentGroup);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DummySiteStatusByPaymentGroupAsync(string dummySiteURL, long operatorId, string paymentGroup) {
            return base.Channel.DummySiteStatusByPaymentGroupAsync(dummySiteURL, operatorId, paymentGroup);
        }
    }
}
