<meta charset="utf-8" />
<meta http-equiv="Content-type" content="text/html;charset=utf-8"/>
<meta name="viewport" id="viewport" content="minimal-ui, width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=no,target-densityDpi=device-dpi" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="apple-mobile-web-app-title" content="W88" />
<link type="text/css" rel="stylesheet" href="/_Static/Css/Mobile/jquery.mobile-1.4.2.min.css" />
<script type="text/javascript" src="/_Static/JS/Mobile/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="/_Static/JS/Mobile/jquery.mobile-1.4.2.min.js"></script>
<script type="text/javascript" src="/_Static/JS/Mobile/iscroll.js"></script>
<script type="text/javascript" src="/_Static/JS/GPINT.js"></script>
<link type="text/css" rel="stylesheet" href="/_Static/Css/Main.css" />
<link rel="apple-touch-icon" href="/_Static/Images/icon_76.png"/>
<link rel="apple-touch-startup-image" href="/_Static/Images/icon_120.png" />
<% if (string.Compare(commonVariables.SelectedLanguage, "th-th", true) == 0) { %>
<link type="text/css" rel="stylesheet" href="/_Static/Css/th-th.css" />
<% } else if (string.Compare(commonVariables.SelectedLanguage, "km-kh", true) == 0) { %>
<link type="text/css" rel="stylesheet" href="/_Static/Css/th-th.css" />
<% } else if (string.Compare(commonVariables.SelectedLanguage, "zh-cn", true) == 0) { %>
<link type="text/css" rel="stylesheet" href="/_Static/Css/zh-cn.css" />
<% } %>