//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W88.WebRef.svcPayMS1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemBankAccount", Namespace="http://schemas.datacontract.org/2004/07/Services")]
    [System.SerializableAttribute()]
    public partial class SystemBankAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long accountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankBranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> bankDowntimeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankNameNativeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dateFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dateToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionExternalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool showBankInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long accountId {
            get {
                return this.accountIdField;
            }
            set {
                if ((this.accountIdField.Equals(value) != true)) {
                    this.accountIdField = value;
                    this.RaisePropertyChanged("accountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accountName {
            get {
                return this.accountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.accountNameField, value) != true)) {
                    this.accountNameField = value;
                    this.RaisePropertyChanged("accountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.accountNumberField, value) != true)) {
                    this.accountNumberField = value;
                    this.RaisePropertyChanged("accountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankBranch {
            get {
                return this.bankBranchField;
            }
            set {
                if ((object.ReferenceEquals(this.bankBranchField, value) != true)) {
                    this.bankBranchField = value;
                    this.RaisePropertyChanged("bankBranch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankCode {
            get {
                return this.bankCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.bankCodeField, value) != true)) {
                    this.bankCodeField = value;
                    this.RaisePropertyChanged("bankCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> bankDowntimeId {
            get {
                return this.bankDowntimeIdField;
            }
            set {
                if ((this.bankDowntimeIdField.Equals(value) != true)) {
                    this.bankDowntimeIdField = value;
                    this.RaisePropertyChanged("bankDowntimeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankNameNative {
            get {
                return this.bankNameNativeField;
            }
            set {
                if ((object.ReferenceEquals(this.bankNameNativeField, value) != true)) {
                    this.bankNameNativeField = value;
                    this.RaisePropertyChanged("bankNameNative");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dateFrom {
            get {
                return this.dateFromField;
            }
            set {
                if ((this.dateFromField.Equals(value) != true)) {
                    this.dateFromField = value;
                    this.RaisePropertyChanged("dateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dateTo {
            get {
                return this.dateToField;
            }
            set {
                if ((this.dateToField.Equals(value) != true)) {
                    this.dateToField = value;
                    this.RaisePropertyChanged("dateTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descriptionExternal {
            get {
                return this.descriptionExternalField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionExternalField, value) != true)) {
                    this.descriptionExternalField = value;
                    this.RaisePropertyChanged("descriptionExternal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool showBankInfo {
            get {
                return this.showBankInfoField;
            }
            set {
                if ((this.showBankInfoField.Equals(value) != true)) {
                    this.showBankInfoField = value;
                    this.RaisePropertyChanged("showBankInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoneyAccount", Namespace="http://schemas.datacontract.org/2004/07/Services")]
    [System.SerializableAttribute()]
    public partial class MoneyAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionExternalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionInternalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWithdrawalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MethodIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OperatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionExternal {
            get {
                return this.DescriptionExternalField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionExternalField, value) != true)) {
                    this.DescriptionExternalField = value;
                    this.RaisePropertyChanged("DescriptionExternal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionInternal {
            get {
                return this.DescriptionInternalField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionInternalField, value) != true)) {
                    this.DescriptionInternalField = value;
                    this.RaisePropertyChanged("DescriptionInternal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeposit {
            get {
                return this.IsDepositField;
            }
            set {
                if ((this.IsDepositField.Equals(value) != true)) {
                    this.IsDepositField = value;
                    this.RaisePropertyChanged("IsDeposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWithdrawal {
            get {
                return this.IsWithdrawalField;
            }
            set {
                if ((this.IsWithdrawalField.Equals(value) != true)) {
                    this.IsWithdrawalField = value;
                    this.RaisePropertyChanged("IsWithdrawal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MethodId {
            get {
                return this.MethodIdField;
            }
            set {
                if ((this.MethodIdField.Equals(value) != true)) {
                    this.MethodIdField = value;
                    this.RaisePropertyChanged("MethodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OperatorId {
            get {
                return this.OperatorIdField;
            }
            set {
                if ((this.OperatorIdField.Equals(value) != true)) {
                    this.OperatorIdField = value;
                    this.RaisePropertyChanged("OperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcPayMS1.IMS1")]
    public interface IMS1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getSystemAccounts", ReplyAction="http://tempuri.org/IMS1/getSystemAccountsResponse")]
        W88.WebRef.svcPayMS1.getSystemAccountsResponse getSystemAccounts(W88.WebRef.svcPayMS1.getSystemAccountsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getSystemAccounts", ReplyAction="http://tempuri.org/IMS1/getSystemAccountsResponse")]
        System.Threading.Tasks.Task<W88.WebRef.svcPayMS1.getSystemAccountsResponse> getSystemAccountsAsync(W88.WebRef.svcPayMS1.getSystemAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getSystemBankAccount", ReplyAction="http://tempuri.org/IMS1/getSystemBankAccountResponse")]
        W88.WebRef.svcPayMS1.getSystemBankAccountResponse getSystemBankAccount(W88.WebRef.svcPayMS1.getSystemBankAccountRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getSystemBankAccount", ReplyAction="http://tempuri.org/IMS1/getSystemBankAccountResponse")]
        System.Threading.Tasks.Task<W88.WebRef.svcPayMS1.getSystemBankAccountResponse> getSystemBankAccountAsync(W88.WebRef.svcPayMS1.getSystemBankAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/uploadFile", ReplyAction="http://tempuri.org/IMS1/uploadFileResponse")]
        W88.WebRef.svcPayMS1.uploadFileResponse uploadFile(W88.WebRef.svcPayMS1.uploadFileRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/uploadFile", ReplyAction="http://tempuri.org/IMS1/uploadFileResponse")]
        System.Threading.Tasks.Task<W88.WebRef.svcPayMS1.uploadFileResponse> uploadFileAsync(W88.WebRef.svcPayMS1.uploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getAffiliateSystemBankAccount", ReplyAction="http://tempuri.org/IMS1/getAffiliateSystemBankAccountResponse")]
        W88.WebRef.svcPayMS1.SystemBankAccount[] getAffiliateSystemBankAccount(long operatorId, long affiliateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getAffiliateSystemBankAccount", ReplyAction="http://tempuri.org/IMS1/getAffiliateSystemBankAccountResponse")]
        System.Threading.Tasks.Task<W88.WebRef.svcPayMS1.SystemBankAccount[]> getAffiliateSystemBankAccountAsync(long operatorId, long affiliateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getCashFlowTransactionByDate", ReplyAction="http://tempuri.org/IMS1/getCashFlowTransactionByDateResponse")]
        System.Data.DataSet getCashFlowTransactionByDate(long operatorId, System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getCashFlowTransactionByDate", ReplyAction="http://tempuri.org/IMS1/getCashFlowTransactionByDateResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getCashFlowTransactionByDateAsync(long operatorId, System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getMoneyAccountFundInListItem", ReplyAction="http://tempuri.org/IMS1/getMoneyAccountFundInListItemResponse")]
        W88.WebRef.svcPayMS1.MoneyAccount[] getMoneyAccountFundInListItem(long operatorId, long methodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getMoneyAccountFundInListItem", ReplyAction="http://tempuri.org/IMS1/getMoneyAccountFundInListItemResponse")]
        System.Threading.Tasks.Task<W88.WebRef.svcPayMS1.MoneyAccount[]> getMoneyAccountFundInListItemAsync(long operatorId, long methodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/encrypt", ReplyAction="http://tempuri.org/IMS1/encryptResponse")]
        string encrypt(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/encrypt", ReplyAction="http://tempuri.org/IMS1/encryptResponse")]
        System.Threading.Tasks.Task<string> encryptAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/decrypt", ReplyAction="http://tempuri.org/IMS1/decryptResponse")]
        string decrypt(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/decrypt", ReplyAction="http://tempuri.org/IMS1/decryptResponse")]
        System.Threading.Tasks.Task<string> decryptAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getPaymentGatewaySetting", ReplyAction="http://tempuri.org/IMS1/getPaymentGatewaySettingResponse")]
        System.Data.DataTable getPaymentGatewaySetting(long operatorId, long methodId, string merchantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getPaymentGatewaySetting", ReplyAction="http://tempuri.org/IMS1/getPaymentGatewaySettingResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getPaymentGatewaySettingAsync(long operatorId, long methodId, string merchantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getBankAccountImage", ReplyAction="http://tempuri.org/IMS1/getBankAccountImageResponse")]
        W88.WebRef.svcPayMS1.getBankAccountImageResponse getBankAccountImage(W88.WebRef.svcPayMS1.getBankAccountImageRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getBankAccountImage", ReplyAction="http://tempuri.org/IMS1/getBankAccountImageResponse")]
        System.Threading.Tasks.Task<W88.WebRef.svcPayMS1.getBankAccountImageResponse> getBankAccountImageAsync(W88.WebRef.svcPayMS1.getBankAccountImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getDepositWithdrawalReport", ReplyAction="http://tempuri.org/IMS1/getDepositWithdrawalReportResponse")]
        string getDepositWithdrawalReport(long operatorId, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getDepositWithdrawalReport", ReplyAction="http://tempuri.org/IMS1/getDepositWithdrawalReportResponse")]
        System.Threading.Tasks.Task<string> getDepositWithdrawalReportAsync(long operatorId, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getOnlineDepositWithdrawalReport", ReplyAction="http://tempuri.org/IMS1/getOnlineDepositWithdrawalReportResponse")]
        string getOnlineDepositWithdrawalReport(long operatorId, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/getOnlineDepositWithdrawalReport", ReplyAction="http://tempuri.org/IMS1/getOnlineDepositWithdrawalReportResponse")]
        System.Threading.Tasks.Task<string> getOnlineDepositWithdrawalReportAsync(long operatorId, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/SDPayEncrypt", ReplyAction="http://tempuri.org/IMS1/SDPayEncryptResponse")]
        string SDPayEncrypt(string data, string key1, string key2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMS1/SDPayEncrypt", ReplyAction="http://tempuri.org/IMS1/SDPayEncryptResponse")]
        System.Threading.Tasks.Task<string> SDPayEncryptAsync(string data, string key1, string key2);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSystemAccounts", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getSystemAccountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string operatorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string memberCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string currencyCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string riskId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string paymentGroup;
        
        public getSystemAccountsRequest() {
        }
        
        public getSystemAccountsRequest(string operatorId, string memberCode, string currencyCode, string countryCode, string riskId, string paymentGroup) {
            this.operatorId = operatorId;
            this.memberCode = memberCode;
            this.currencyCode = currencyCode;
            this.countryCode = countryCode;
            this.riskId = riskId;
            this.paymentGroup = paymentGroup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSystemAccountsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getSystemAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable bankAccountsDataTable;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string processCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string processText;
        
        public getSystemAccountsResponse() {
        }
        
        public getSystemAccountsResponse(System.Data.DataTable bankAccountsDataTable, string processCode, string processText) {
            this.bankAccountsDataTable = bankAccountsDataTable;
            this.processCode = processCode;
            this.processText = processText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSystemBankAccount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getSystemBankAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long operatorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string memberCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Nullable<bool> isAlipay;
        
        public getSystemBankAccountRequest() {
        }
        
        public getSystemBankAccountRequest(long operatorId, string memberCode, System.Nullable<bool> isAlipay) {
            this.operatorId = operatorId;
            this.memberCode = memberCode;
            this.isAlipay = isAlipay;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSystemBankAccountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getSystemBankAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public W88.WebRef.svcPayMS1.SystemBankAccount[] getSystemBankAccountResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string statusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string statusText;
        
        public getSystemBankAccountResponse() {
        }
        
        public getSystemBankAccountResponse(W88.WebRef.svcPayMS1.SystemBankAccount[] getSystemBankAccountResult, string statusCode, string statusText) {
            this.getSystemBankAccountResult = getSystemBankAccountResult;
            this.statusCode = statusCode;
            this.statusText = statusText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class uploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long operatorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string memberCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string memberName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public long invId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte[] fileStream;
        
        public uploadFileRequest() {
        }
        
        public uploadFileRequest(long operatorId, string memberCode, string memberName, long invId, string fileName, byte[] fileStream) {
            this.operatorId = operatorId;
            this.memberCode = memberCode;
            this.memberName = memberName;
            this.invId = invId;
            this.fileName = fileName;
            this.fileStream = fileStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class uploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool uploadFileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string statusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string statusText;
        
        public uploadFileResponse() {
        }
        
        public uploadFileResponse(bool uploadFileResult, string statusCode, string statusText) {
            this.uploadFileResult = uploadFileResult;
            this.statusCode = statusCode;
            this.statusText = statusText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBankAccountImage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getBankAccountImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long accountId;
        
        public getBankAccountImageRequest() {
        }
        
        public getBankAccountImageRequest(long accountId) {
            this.accountId = accountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBankAccountImageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getBankAccountImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool getBankAccountImageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string contentType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string contentCoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte[] contentData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public long contentLength;
        
        public getBankAccountImageResponse() {
        }
        
        public getBankAccountImageResponse(bool getBankAccountImageResult, string fileName, string contentType, string contentCoding, byte[] contentData, long contentLength) {
            this.getBankAccountImageResult = getBankAccountImageResult;
            this.fileName = fileName;
            this.contentType = contentType;
            this.contentCoding = contentCoding;
            this.contentData = contentData;
            this.contentLength = contentLength;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMS1Channel : W88.WebRef.svcPayMS1.IMS1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MS1Client : System.ServiceModel.ClientBase<W88.WebRef.svcPayMS1.IMS1>, W88.WebRef.svcPayMS1.IMS1 {
        
        public MS1Client() {
        }
        
        public MS1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MS1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MS1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MS1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W88.WebRef.svcPayMS1.getSystemAccountsResponse W88.WebRef.svcPayMS1.IMS1.getSystemAccounts(W88.WebRef.svcPayMS1.getSystemAccountsRequest request) {
            return base.Channel.getSystemAccounts(request);
        }
        
        public System.Data.DataTable getSystemAccounts(string operatorId, string memberCode, string currencyCode, string countryCode, string riskId, string paymentGroup, out string processCode, out string processText) {
            W88.WebRef.svcPayMS1.getSystemAccountsRequest inValue = new W88.WebRef.svcPayMS1.getSystemAccountsRequest();
            inValue.operatorId = operatorId;
            inValue.memberCode = memberCode;
            inValue.currencyCode = currencyCode;
            inValue.countryCode = countryCode;
            inValue.riskId = riskId;
            inValue.paymentGroup = paymentGroup;
            W88.WebRef.svcPayMS1.getSystemAccountsResponse retVal = ((W88.WebRef.svcPayMS1.IMS1)(this)).getSystemAccounts(inValue);
            processCode = retVal.processCode;
            processText = retVal.processText;
            return retVal.bankAccountsDataTable;
        }
        
        public System.Threading.Tasks.Task<W88.WebRef.svcPayMS1.getSystemAccountsResponse> getSystemAccountsAsync(W88.WebRef.svcPayMS1.getSystemAccountsRequest request) {
            return base.Channel.getSystemAccountsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W88.WebRef.svcPayMS1.getSystemBankAccountResponse W88.WebRef.svcPayMS1.IMS1.getSystemBankAccount(W88.WebRef.svcPayMS1.getSystemBankAccountRequest request) {
            return base.Channel.getSystemBankAccount(request);
        }
        
        public W88.WebRef.svcPayMS1.SystemBankAccount[] getSystemBankAccount(long operatorId, string memberCode, System.Nullable<bool> isAlipay, out string statusCode, out string statusText) {
            W88.WebRef.svcPayMS1.getSystemBankAccountRequest inValue = new W88.WebRef.svcPayMS1.getSystemBankAccountRequest();
            inValue.operatorId = operatorId;
            inValue.memberCode = memberCode;
            inValue.isAlipay = isAlipay;
            W88.WebRef.svcPayMS1.getSystemBankAccountResponse retVal = ((W88.WebRef.svcPayMS1.IMS1)(this)).getSystemBankAccount(inValue);
            statusCode = retVal.statusCode;
            statusText = retVal.statusText;
            return retVal.getSystemBankAccountResult;
        }
        
        public System.Threading.Tasks.Task<W88.WebRef.svcPayMS1.getSystemBankAccountResponse> getSystemBankAccountAsync(W88.WebRef.svcPayMS1.getSystemBankAccountRequest request) {
            return base.Channel.getSystemBankAccountAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W88.WebRef.svcPayMS1.uploadFileResponse W88.WebRef.svcPayMS1.IMS1.uploadFile(W88.WebRef.svcPayMS1.uploadFileRequest request) {
            return base.Channel.uploadFile(request);
        }
        
        public bool uploadFile(long operatorId, string memberCode, string memberName, long invId, string fileName, byte[] fileStream, out string statusCode, out string statusText) {
            W88.WebRef.svcPayMS1.uploadFileRequest inValue = new W88.WebRef.svcPayMS1.uploadFileRequest();
            inValue.operatorId = operatorId;
            inValue.memberCode = memberCode;
            inValue.memberName = memberName;
            inValue.invId = invId;
            inValue.fileName = fileName;
            inValue.fileStream = fileStream;
            W88.WebRef.svcPayMS1.uploadFileResponse retVal = ((W88.WebRef.svcPayMS1.IMS1)(this)).uploadFile(inValue);
            statusCode = retVal.statusCode;
            statusText = retVal.statusText;
            return retVal.uploadFileResult;
        }
        
        public System.Threading.Tasks.Task<W88.WebRef.svcPayMS1.uploadFileResponse> uploadFileAsync(W88.WebRef.svcPayMS1.uploadFileRequest request) {
            return base.Channel.uploadFileAsync(request);
        }
        
        public W88.WebRef.svcPayMS1.SystemBankAccount[] getAffiliateSystemBankAccount(long operatorId, long affiliateId) {
            return base.Channel.getAffiliateSystemBankAccount(operatorId, affiliateId);
        }
        
        public System.Threading.Tasks.Task<W88.WebRef.svcPayMS1.SystemBankAccount[]> getAffiliateSystemBankAccountAsync(long operatorId, long affiliateId) {
            return base.Channel.getAffiliateSystemBankAccountAsync(operatorId, affiliateId);
        }
        
        public System.Data.DataSet getCashFlowTransactionByDate(long operatorId, System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.getCashFlowTransactionByDate(operatorId, dateFrom, dateTo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getCashFlowTransactionByDateAsync(long operatorId, System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.getCashFlowTransactionByDateAsync(operatorId, dateFrom, dateTo);
        }
        
        public W88.WebRef.svcPayMS1.MoneyAccount[] getMoneyAccountFundInListItem(long operatorId, long methodId) {
            return base.Channel.getMoneyAccountFundInListItem(operatorId, methodId);
        }
        
        public System.Threading.Tasks.Task<W88.WebRef.svcPayMS1.MoneyAccount[]> getMoneyAccountFundInListItemAsync(long operatorId, long methodId) {
            return base.Channel.getMoneyAccountFundInListItemAsync(operatorId, methodId);
        }
        
        public string encrypt(string input) {
            return base.Channel.encrypt(input);
        }
        
        public System.Threading.Tasks.Task<string> encryptAsync(string input) {
            return base.Channel.encryptAsync(input);
        }
        
        public string decrypt(string input) {
            return base.Channel.decrypt(input);
        }
        
        public System.Threading.Tasks.Task<string> decryptAsync(string input) {
            return base.Channel.decryptAsync(input);
        }
        
        public System.Data.DataTable getPaymentGatewaySetting(long operatorId, long methodId, string merchantId) {
            return base.Channel.getPaymentGatewaySetting(operatorId, methodId, merchantId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getPaymentGatewaySettingAsync(long operatorId, long methodId, string merchantId) {
            return base.Channel.getPaymentGatewaySettingAsync(operatorId, methodId, merchantId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W88.WebRef.svcPayMS1.getBankAccountImageResponse W88.WebRef.svcPayMS1.IMS1.getBankAccountImage(W88.WebRef.svcPayMS1.getBankAccountImageRequest request) {
            return base.Channel.getBankAccountImage(request);
        }
        
        public bool getBankAccountImage(long accountId, out string fileName, out string contentType, out string contentCoding, out byte[] contentData, out long contentLength) {
            W88.WebRef.svcPayMS1.getBankAccountImageRequest inValue = new W88.WebRef.svcPayMS1.getBankAccountImageRequest();
            inValue.accountId = accountId;
            W88.WebRef.svcPayMS1.getBankAccountImageResponse retVal = ((W88.WebRef.svcPayMS1.IMS1)(this)).getBankAccountImage(inValue);
            fileName = retVal.fileName;
            contentType = retVal.contentType;
            contentCoding = retVal.contentCoding;
            contentData = retVal.contentData;
            contentLength = retVal.contentLength;
            return retVal.getBankAccountImageResult;
        }
        
        public System.Threading.Tasks.Task<W88.WebRef.svcPayMS1.getBankAccountImageResponse> getBankAccountImageAsync(W88.WebRef.svcPayMS1.getBankAccountImageRequest request) {
            return base.Channel.getBankAccountImageAsync(request);
        }
        
        public string getDepositWithdrawalReport(long operatorId, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate) {
            return base.Channel.getDepositWithdrawalReport(operatorId, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<string> getDepositWithdrawalReportAsync(long operatorId, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate) {
            return base.Channel.getDepositWithdrawalReportAsync(operatorId, startDate, endDate);
        }
        
        public string getOnlineDepositWithdrawalReport(long operatorId, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate) {
            return base.Channel.getOnlineDepositWithdrawalReport(operatorId, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<string> getOnlineDepositWithdrawalReportAsync(long operatorId, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate) {
            return base.Channel.getOnlineDepositWithdrawalReportAsync(operatorId, startDate, endDate);
        }
        
        public string SDPayEncrypt(string data, string key1, string key2) {
            return base.Channel.SDPayEncrypt(data, key1, key2);
        }
        
        public System.Threading.Tasks.Task<string> SDPayEncryptAsync(string data, string key1, string key2) {
            return base.Channel.SDPayEncryptAsync(data, key1, key2);
        }
    }
}
